--customer table data
insert into customer (age) values (18);
insert into customer (age) values (19);
insert into customer (age) values (20);
insert into customer (age) values (21);
insert into customer (age) values (22);
insert into customer (age) values (23);
insert into customer (age) values (24);
insert into customer (age) values (25);
insert into customer (age) values (26);
insert into customer (age) values (27);
insert into customer (age) values (28);
insert into customer (age) values (29);
insert into customer (age) values (30);
insert into customer (age) values (31);
insert into customer (age) values (32);
insert into customer (age) values (33);
insert into customer (age) values (34);
insert into customer (age) values (35);

--items
insert into items (item_name) values ('x');
insert into items (item_name) values ('y');
insert into items (item_name) values ('z');

--sales
insert into sales (customer_id) values (1);
insert into sales (customer_id) values (2);
insert into sales (customer_id) values (3);
insert into sales (customer_id) values (4);
insert into sales (customer_id) values (5);
insert into sales (customer_id) values (6);
insert into sales (customer_id) values (7);
insert into sales (customer_id) values (8);
insert into sales (customer_id) values (9);
insert into sales (customer_id) values (10);
insert into sales (customer_id) values (11);
insert into sales (customer_id) values (12);
insert into sales (customer_id) values (13);
insert into sales (customer_id) values (14);
insert into sales (customer_id) values (15);
insert into sales (customer_id) values (16);
insert into sales (customer_id) values (17);
insert into sales (customer_id) values (18);
insert into sales (customer_id) values (5);
insert into sales (customer_id) values (12);
insert into sales (customer_id) values (3);
insert into sales (customer_id) values (17);
insert into sales (customer_id) values (9);
insert into sales (customer_id) values (1);
insert into sales (customer_id) values (14);
insert into sales (customer_id) values (6);
insert into sales (customer_id) values (18);
insert into sales (customer_id) values (4);
insert into sales (customer_id) values (11);
insert into sales (customer_id) values (7);
insert into sales (customer_id) values (2);
insert into sales (customer_id) values (16);
insert into sales (customer_id) values (10);
insert into sales (customer_id) values (8);
insert into sales (customer_id) values (13);
insert into sales (customer_id) values (15);
insert into sales (customer_id) values (6);
insert into sales (customer_id) values (3);
insert into sales (customer_id) values (12);
insert into sales (customer_id) values (9);
insert into sales (customer_id) values (1);
insert into sales (customer_id) values (17);
insert into sales (customer_id) values (4);
insert into sales (customer_id) values (18);
insert into sales (customer_id) values (7);
insert into sales (customer_id) values (14);
insert into sales (customer_id) values (2);
insert into sales (customer_id) values (11);
insert into sales (customer_id) values (5);
insert into sales (customer_id) values (16);

--orders
INSERT INTO orders (sales_id, item_id, quantity) VALUES (1, 2, 142);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (2, 1, 289);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (3, 3, 56);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (4, 2, 211);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (5, 1, 13);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (6, 3, 198);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (7, 2, 74);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (8, 1, 267);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (9, 3, 122);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (10, 2, 45);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (11, 1, 183);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (12, 3, 299);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (13, 2, 88);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (14, 1, 156);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (15, 3, 23);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (16, 2, 204);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (17, 1, 117);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (18, 3, 62);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (19, 2, 275);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (20, 1, 134);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (21, 3, 91);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (22, 2, 38);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (23, 1, 246);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (24, 3, 172);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (25, 2, 5);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (26, 1, 190);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (27, 3, 222);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (28, 2, 109);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (29, 1, 258);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (30, 3, 41);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (31, 2, 147);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (32, 1, 281);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (33, 3, 69);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (34, 2, 195);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (35, 1, 32);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (36, 3, 112);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (37, 2, 230);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (38, 1, 84);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (39, 3, 263);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (40, 2, 15);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (41, 1, 177);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (42, 3, 292);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (43, 2, 54);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (44, 1, 208);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (45, 3, 129);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (46, 2, 96);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (47, 1, 241);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (48, 3, 18);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (49, 2, 270);
INSERT INTO orders (sales_id, item_id, quantity) VALUES (50, 1, 161);
